# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permuted_entropy_cache.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='permuted_entropy_cache.proto',
  package='variations',
  syntax='proto2',
  serialized_pb=_b('\n\x1cpermuted_entropy_cache.proto\x12\nvariations\"\x81\x01\n\x14PermutedEntropyCache\x12\x35\n\x05\x65ntry\x18\x01 \x03(\x0b\x32&.variations.PermutedEntropyCache.Entry\x1a\x32\n\x05\x45ntry\x12\x1a\n\x12randomization_seed\x18\x01 \x02(\r\x12\r\n\x05value\x18\x02 \x02(\rB\x02H\x03')
)




_PERMUTEDENTROPYCACHE_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='variations.PermutedEntropyCache.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='randomization_seed', full_name='variations.PermutedEntropyCache.Entry.randomization_seed', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='variations.PermutedEntropyCache.Entry.value', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=174,
)

_PERMUTEDENTROPYCACHE = _descriptor.Descriptor(
  name='PermutedEntropyCache',
  full_name='variations.PermutedEntropyCache',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='variations.PermutedEntropyCache.entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PERMUTEDENTROPYCACHE_ENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=174,
)

_PERMUTEDENTROPYCACHE_ENTRY.containing_type = _PERMUTEDENTROPYCACHE
_PERMUTEDENTROPYCACHE.fields_by_name['entry'].message_type = _PERMUTEDENTROPYCACHE_ENTRY
DESCRIPTOR.message_types_by_name['PermutedEntropyCache'] = _PERMUTEDENTROPYCACHE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PermutedEntropyCache = _reflection.GeneratedProtocolMessageType('PermutedEntropyCache', (_message.Message,), dict(

  Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), dict(
    DESCRIPTOR = _PERMUTEDENTROPYCACHE_ENTRY,
    __module__ = 'permuted_entropy_cache_pb2'
    # @@protoc_insertion_point(class_scope:variations.PermutedEntropyCache.Entry)
    ))
  ,
  DESCRIPTOR = _PERMUTEDENTROPYCACHE,
  __module__ = 'permuted_entropy_cache_pb2'
  # @@protoc_insertion_point(class_scope:variations.PermutedEntropyCache)
  ))
_sym_db.RegisterMessage(PermutedEntropyCache)
_sym_db.RegisterMessage(PermutedEntropyCache.Entry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
