# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_worker_types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_worker_types.proto',
  package='content.proto.internal',
  syntax='proto2',
  serialized_pb=_b('\n\x1aservice_worker_types.proto\x12\x16\x63ontent.proto.internal\"\x8c\x04\n\x19ServiceWorkerFetchRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12O\n\x07headers\x18\x03 \x03(\x0b\x32>.content.proto.internal.ServiceWorkerFetchRequest.HeadersEntry\x12L\n\x08referrer\x18\x04 \x01(\x0b\x32:.content.proto.internal.ServiceWorkerFetchRequest.Referrer\x12\x11\n\tis_reload\x18\x05 \x01(\x08\x12\x0c\n\x04mode\x18\x06 \x01(\x05\x12\x1d\n\x15is_main_resource_load\x18\x07 \x01(\x08\x12\x1c\n\x14request_context_type\x18\x08 \x01(\x05\x12\x18\n\x10\x63redentials_mode\x18\t \x01(\x05\x12\x12\n\ncache_mode\x18\n \x01(\x05\x12\x15\n\rredirect_mode\x18\x0b \x01(\x05\x12\x11\n\tintegrity\x18\x0c \x01(\t\x12\x11\n\tkeepalive\x18\r \x01(\x08\x12\x11\n\tclient_id\x18\x0e \x01(\t\x1a\'\n\x08Referrer\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0e\n\x06policy\x18\x02 \x01(\x05\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x02H\x03')
)




_SERVICEWORKERFETCHREQUEST_REFERRER = _descriptor.Descriptor(
  name='Referrer',
  full_name='content.proto.internal.ServiceWorkerFetchRequest.Referrer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='content.proto.internal.ServiceWorkerFetchRequest.Referrer.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='policy', full_name='content.proto.internal.ServiceWorkerFetchRequest.Referrer.policy', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=531,
)

_SERVICEWORKERFETCHREQUEST_HEADERSENTRY = _descriptor.Descriptor(
  name='HeadersEntry',
  full_name='content.proto.internal.ServiceWorkerFetchRequest.HeadersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='content.proto.internal.ServiceWorkerFetchRequest.HeadersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='content.proto.internal.ServiceWorkerFetchRequest.HeadersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=533,
  serialized_end=579,
)

_SERVICEWORKERFETCHREQUEST = _descriptor.Descriptor(
  name='ServiceWorkerFetchRequest',
  full_name='content.proto.internal.ServiceWorkerFetchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='content.proto.internal.ServiceWorkerFetchRequest.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='method', full_name='content.proto.internal.ServiceWorkerFetchRequest.method', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='headers', full_name='content.proto.internal.ServiceWorkerFetchRequest.headers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='referrer', full_name='content.proto.internal.ServiceWorkerFetchRequest.referrer', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_reload', full_name='content.proto.internal.ServiceWorkerFetchRequest.is_reload', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mode', full_name='content.proto.internal.ServiceWorkerFetchRequest.mode', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_main_resource_load', full_name='content.proto.internal.ServiceWorkerFetchRequest.is_main_resource_load', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_context_type', full_name='content.proto.internal.ServiceWorkerFetchRequest.request_context_type', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='credentials_mode', full_name='content.proto.internal.ServiceWorkerFetchRequest.credentials_mode', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cache_mode', full_name='content.proto.internal.ServiceWorkerFetchRequest.cache_mode', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='redirect_mode', full_name='content.proto.internal.ServiceWorkerFetchRequest.redirect_mode', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='integrity', full_name='content.proto.internal.ServiceWorkerFetchRequest.integrity', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keepalive', full_name='content.proto.internal.ServiceWorkerFetchRequest.keepalive', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='content.proto.internal.ServiceWorkerFetchRequest.client_id', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SERVICEWORKERFETCHREQUEST_REFERRER, _SERVICEWORKERFETCHREQUEST_HEADERSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=579,
)

_SERVICEWORKERFETCHREQUEST_REFERRER.containing_type = _SERVICEWORKERFETCHREQUEST
_SERVICEWORKERFETCHREQUEST_HEADERSENTRY.containing_type = _SERVICEWORKERFETCHREQUEST
_SERVICEWORKERFETCHREQUEST.fields_by_name['headers'].message_type = _SERVICEWORKERFETCHREQUEST_HEADERSENTRY
_SERVICEWORKERFETCHREQUEST.fields_by_name['referrer'].message_type = _SERVICEWORKERFETCHREQUEST_REFERRER
DESCRIPTOR.message_types_by_name['ServiceWorkerFetchRequest'] = _SERVICEWORKERFETCHREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceWorkerFetchRequest = _reflection.GeneratedProtocolMessageType('ServiceWorkerFetchRequest', (_message.Message,), dict(

  Referrer = _reflection.GeneratedProtocolMessageType('Referrer', (_message.Message,), dict(
    DESCRIPTOR = _SERVICEWORKERFETCHREQUEST_REFERRER,
    __module__ = 'service_worker_types_pb2'
    # @@protoc_insertion_point(class_scope:content.proto.internal.ServiceWorkerFetchRequest.Referrer)
    ))
  ,

  HeadersEntry = _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), dict(
    DESCRIPTOR = _SERVICEWORKERFETCHREQUEST_HEADERSENTRY,
    __module__ = 'service_worker_types_pb2'
    # @@protoc_insertion_point(class_scope:content.proto.internal.ServiceWorkerFetchRequest.HeadersEntry)
    ))
  ,
  DESCRIPTOR = _SERVICEWORKERFETCHREQUEST,
  __module__ = 'service_worker_types_pb2'
  # @@protoc_insertion_point(class_scope:content.proto.internal.ServiceWorkerFetchRequest)
  ))
_sym_db.RegisterMessage(ServiceWorkerFetchRequest)
_sym_db.RegisterMessage(ServiceWorkerFetchRequest.Referrer)
_sym_db.RegisterMessage(ServiceWorkerFetchRequest.HeadersEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
_SERVICEWORKERFETCHREQUEST_HEADERSENTRY.has_options = True
_SERVICEWORKERFETCHREQUEST_HEADERSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
